spring:
  application:
    name: Tradepilot-ai
  ai:
    ollama:
      base-url: http://localhost:12434
      chat:
        options:
          model: qwen3
          temperature: 0.2
    mcp:
      client:
        enabled: true
        name: Tradepilot-mcp-client
        version: 1.0.0
        request-timeout: 30s
        type: SYNC  # or ASYNC for reactive applications
        streamable-http:
          connections:
            kites-mcp:
              url: https://mcp.kite.trade/mcp
logging:
  level:
    org.springframework.ai.mcp: DEBUG
    org.springframework.ai.ollama: DEBUG